### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by JasCodes** [mcernusca/use-key-state#1]
Are you interested in typescript support?

**Comment by mcernusca** [comment]
I have only superficial experience with TS but if you have a need for it then yeah that would be great.

**Comment by mcernusca** [comment]
@jas99 just to clarify, are you offering to add or asking for TS support?

**Comment by JasCodes** [comment]
@mcernusca Well I rather have you do it :stuck_out_tongue: ;But if I have some extra time on my hands, I might just rewrite your code in Typescript.

**Comment by mcernusca** [comment]
Haha sorry, I misread! I'll take a stab at adding type information for now when I get a chance. I'm more concerned with people being able to use it easily from Typescript rather than having to maintain it in Typescript. Since it is still one file I do like that it someone can copy paste it and include it in a normal project. If the size of the codebase grows then it might make sense to port it over.

**Comment by mcernusca** [comment]
@jas99 just pushed the type definitions. I wish there was a way to express that the keys of the return match the keys of the input so auto complete would work. If you have ideas for how to improve it let me know! Thanks

**Comment by JasCodes** [comment]
@mcernusca 	Awesome man... you beat me to it. Lemme test it out. Also I didn't understood `keys of the return match the keys of the input`.

I will follow on with feedback.

Thx

**Comment by JasCodes** [comment]
@mcernusca Oh I see what you meant, one need to use generic types to solve this. Lemme send you PR when I have little time.

**Comment by mcernusca** [comment]
Loving it, thanks again. Published 0.1.6 with your changes @jas99 🎉

**Comment by JasCodes** [comment]
FYI I split KeyStates into two types and then merge back because of https://github.com/Microsoft/TypeScript/issues/13573.
